spring.application.name=recommendatio-engine

# Movie's api key
omdb.api.key=5176f8e5

# Mongo DB
spring.data.mongodb.uri=mongodb+srv://spring_user:recommsyst123@cluster0.8vngx9t.mongodb.net/recsysdb?retryWrites=true&w=majority&appName=Cluster0

# TMDB api key
tmdb.api.key=1b184da9ac25353e5631393f23525b1e

# TMDB base uri
tmdb.api.baseurl=https://api.themoviedb.org/3

