spring.application.name=${SPRING_APPLICATION_NAME:recommendatio-engine}

# Mongo DB
spring.data.mongodb.uri=${SPRING_MONGO_URI}

# TMDB api key
tmdb.api.key=${TMDB_API_KEY}

# TMDB base uri
tmdb.api.baseurl=${TMDB_API_BASEURL:https://api.themoviedb.org/3}

app.python.command=${APP_PYTHON_COMMAND:python3}
app.python.script-path=${APP_PYTHON_SCRIPT_PATH:./python_agent/batch_processor.py}

# Redis credentials
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
